window.ENGS3_VOCAB_DATA = {
    primaryVocabularyList: [
        {"word": "space", "type": "n.", "unit": "小学难度", "meaning": "空间；太空"},
        {"word": "book", "type": "n.", "unit": "小学难度", "meaning": "书"},
        {"word": "water", "type": "n.", "unit": "小学难度", "meaning": "水"},
        {"word": "school", "type": "n.", "unit": "小学难度", "meaning": "学校"},
        {"word": "friend", "type": "n.", "unit": "小学难度", "meaning": "朋友"},
        {"word": "family", "type": "n.", "unit": "小学难度", "meaning": "家庭"},
        {"word": "teacher", "type": "n.", "unit": "小学难度", "meaning": "老师"},
        {"word": "student", "type": "n.", "unit": "小学难度", "meaning": "学生"},
        {"word": "happy", "type": "adj.", "unit": "小学难度", "meaning": "开心的"},
        {"word": "small", "type": "adj.", "unit": "小学难度", "meaning": "小的"},
        {"word": "big", "type": "adj.", "unit": "小学难度", "meaning": "大的"},
        {"word": "clean", "type": "adj.", "unit": "小学难度", "meaning": "干净的"},
        {"word": "run", "type": "v.", "unit": "小学难度", "meaning": "跑"},
        {"word": "read", "type": "v.", "unit": "小学难度", "meaning": "阅读"},
        {"word": "write", "type": "v.", "unit": "小学难度", "meaning": "写"},
        {"word": "play", "type": "v.", "unit": "小学难度", "meaning": "玩"},
        {"word": "eat", "type": "v.", "unit": "小学难度", "meaning": "吃"},
        {"word": "drink", "type": "v.", "unit": "小学难度", "meaning": "喝"},
        {"word": "today", "type": "adv.", "unit": "小学难度", "meaning": "今天"},
        {"word": "always", "type": "adv.", "unit": "小学难度", "meaning": "总是"}
    ],

    fullVocabularyList: [
        {"word": "artificial intelligence", "type": "n. phr.", "unit": "Unit 5", "meaning": "人工智能"},
        {"word": "augmented reality", "type": "n. phr.", "unit": "Unit 5", "meaning": "增强现实"},
        {"word": "autopilot", "type": "n.", "unit": "Unit 5", "meaning": "自动驾驶"},
        {"word": "charging station", "type": "n. phr.", "unit": "Unit 5", "meaning": "充电站"},
        {"word": "chatbot", "type": "n.", "unit": "Unit 5", "meaning": "聊天机器人"},
        {"word": "cultured meat", "type": "n. phr.", "unit": "Unit 5", "meaning": "人造肉"},
        {"word": "digital consumer", "type": "n. phr.", "unit": "Unit 5", "meaning": "数字消费者"},
        {"word": "electronic communication", "type": "n. phr.", "unit": "Unit 5", "meaning": "电子通信"},
        {"word": "facial recognition", "type": "n. phr.", "unit": "Unit 5", "meaning": "面部识别"},
        {"word": "flying car", "type": "n. phr.", "unit": "Unit 5", "meaning": "飞行汽车"},
        {"word": "gene therapy", "type": "n. phr.", "unit": "Unit 5", "meaning": "基因治疗"},
        {"word": "hacking", "type": "n.", "unit": "Unit 5", "meaning": "网络黑客行为"},
        {"word": "hologram", "type": "n.", "unit": "Unit 5", "meaning": "全息图"},
        {"word": "in vitro", "type": "adj.", "unit": "Unit 5", "meaning": "体外"},
        {"word": "nanotechnology", "type": "n.", "unit": "Unit 5", "meaning": "纳米技术"},
        {"word": "notification", "type": "n.", "unit": "Unit 5", "meaning": "通知"},
        {"word": "robotics", "type": "n.", "unit": "Unit 5", "meaning": "机器人学"},
        {"word": "search engine", "type": "n. phr.", "unit": "Unit 5", "meaning": "搜索引擎"},
        {"word": "selective breeding", "type": "n. phr.", "unit": "Unit 5", "meaning": "选择性育种"},
        {"word": "smart personal assistant", "type": "n. phr.", "unit": "Unit 5", "meaning": "智能个人助理"},
        {"word": "space tourism", "type": "n. phr.", "unit": "Unit 5", "meaning": "太空旅游"},
        {"word": "super crop", "type": "n. phr.", "unit": "Unit 5", "meaning": "超级作物"},
        {"word": "virtual reality", "type": "n. phr.", "unit": "Unit 5", "meaning": "虚拟现实"},
        {"word": "adapt", "type": "v.", "unit": "Unit 5", "meaning": "适应"},
        {"word": "blue light", "type": "n. phr.", "unit": "Unit 5", "meaning": "蓝光"},
        {"word": "breakthrough", "type": "n.", "unit": "Unit 5", "meaning": "突破"},
        {"word": "driverless", "type": "adj.", "unit": "Unit 5", "meaning": "无人驾驶的"},
        {"word": "exponentially", "type": "adv.", "unit": "Unit 5", "meaning": "指数级地"},
        {"word": "game-changing", "type": "adj.", "unit": "Unit 5", "meaning": "颠覆性的/改变游戏规则的"},
        {"word": "genetically engineered", "type": "adj.", "unit": "Unit 5", "meaning": "转基因的"},
        {"word": "initiative", "type": "n.", "unit": "Unit 5", "meaning": "主动权/措施"},
        {"word": "intimidating", "type": "adj.", "unit": "Unit 5", "meaning": "令人不安的/吓人的"},
        {"word": "lab-grown", "type": "adj.", "unit": "Unit 5", "meaning": "实验室培育的"},
        {"word": "plant-based", "type": "adj.", "unit": "Unit 5", "meaning": "植物基的"},
        {"word": "programmed", "type": "adj.", "unit": "Unit 5", "meaning": "预编程的"},
        {"word": "radical", "type": "adj.", "unit": "Unit 5", "meaning": "根本的/全新的"},
        {"word": "redefine", "type": "v.", "unit": "Unit 5", "meaning": "重新定义"},
        {"word": "reimagine", "type": "v.", "unit": "Unit 5", "meaning": "重新构想"},
        {"word": "shift", "type": "n.", "unit": "Unit 5", "meaning": "转变"},
        {"word": "transform", "type": "v.", "unit": "Unit 5", "meaning": "改造/转型"},
        {"word": "unprecedented", "type": "adj.", "unit": "Unit 5", "meaning": "前所未有的"},
        {"word": "virtual", "type": "adj.", "unit": "Unit 5", "meaning": "虚拟的"},
        {"word": "address", "type": "v.", "unit": "Unit 5", "meaning": "演讲/处理"},
        {"word": "complementary", "type": "adj.", "unit": "Unit 5", "meaning": "互补的"},
        {"word": "complimentary", "type": "adj.", "unit": "Unit 5", "meaning": "赞美的/免费的"},
        {"word": "groan", "type": "v.", "unit": "Unit 5", "meaning": "呻吟/抱怨"},
        {"word": "idle", "type": "adj.", "unit": "Unit 5", "meaning": "闲置的/无所事事的"},
        {"word": "idol", "type": "n.", "unit": "Unit 5", "meaning": "偶像"},
        {"word": "install", "type": "v.", "unit": "Unit 5", "meaning": "安装"},
        {"word": "remote", "type": "adj.", "unit": "Unit 5", "meaning": "远程的/偏远的"},
        {"word": "saver", "type": "n.", "unit": "Unit 5", "meaning": "节约者/储蓄者"},
        {"word": "savour", "type": "v.", "unit": "Unit 5", "meaning": "品尝/欣赏"},
        {"word": "season", "type": "v.", "unit": "Unit 5", "meaning": "调味/使适应"},
        {"word": "stationary", "type": "adj.", "unit": "Unit 5", "meaning": "静止的/固定的"},
        {"word": "stationery", "type": "n.", "unit": "Unit 5", "meaning": "文具"},
        {"word": "abandoned fishing net", "type": "n. phr.", "unit": "Unit 6", "meaning": "废弃渔网"},
        {"word": "coral bleaching", "type": "n. phr.", "unit": "Unit 6", "meaning": "珊瑚白化"},
        {"word": "deforestation", "type": "n.", "unit": "Unit 6", "meaning": "滥伐森林"},
        {"word": "erosion", "type": "n.", "unit": "Unit 6", "meaning": "侵蚀"},
        {"word": "extreme weather event", "type": "n. phr.", "unit": "Unit 6", "meaning": "极端天气事件"},
        {"word": "food waste", "type": "n. phr.", "unit": "Unit 6", "meaning": "食品浪费"},
        {"word": "global warming", "type": "n. phr.", "unit": "Unit 6", "meaning": "全球变暖"},
        {"word": "household waste", "type": "n. phr.", "unit": "Unit 6", "meaning": "家庭垃圾"},
        {"word": "light pollution", "type": "n. phr.", "unit": "Unit 6", "meaning": "光污染"},
        {"word": "lower diversity", "type": "n. phr.", "unit": "Unit 6", "meaning": "降低多样性"},
        {"word": "microfibre", "type": "n.", "unit": "Unit 6", "meaning": "微纤维"},
        {"word": "microplastic", "type": "n.", "unit": "Unit 6", "meaning": "微塑料"},
        {"word": "overpopulation", "type": "n.", "unit": "Unit 6", "meaning": "人口过剩"},
        {"word": "plastic pollution", "type": "n. phr.", "unit": "Unit 6", "meaning": "塑料污染"},
        {"word": "rising sea temperature", "type": "n. phr.", "unit": "Unit 6", "meaning": "海水温度上升"},
        {"word": "single-use plasticware", "type": "n. phr.", "unit": "Unit 6", "meaning": "一次性塑料器皿"},
        {"word": "toxic residue", "type": "n. phr.", "unit": "Unit 6", "meaning": "有毒残留物"},
        {"word": "vehicle emissions", "type": "n. phr.", "unit": "Unit 6", "meaning": "汽车尾气"},
        {"word": "wastewater", "type": "n.", "unit": "Unit 6", "meaning": "废水"},
        {"word": "biodegradable", "type": "adj.", "unit": "Unit 6", "meaning": "可生物降解的"},
        {"word": "compost", "type": "n.", "unit": "Unit 6", "meaning": "堆肥"},
        {"word": "conserve", "type": "v.", "unit": "Unit 6", "meaning": "保护/节约"},
        {"word": "coral reef", "type": "n. phr.", "unit": "Unit 6", "meaning": "珊瑚礁"},
        {"word": "discard", "type": "v.", "unit": "Unit 6", "meaning": "丢弃"},
        {"word": "eco-friendly", "type": "adj.", "unit": "Unit 6", "meaning": "环保的"},
        {"word": "ecosystem", "type": "n.", "unit": "Unit 6", "meaning": "生态系统"},
        {"word": "energy-efficient", "type": "adj.", "unit": "Unit 6", "meaning": "节能的"},
        {"word": "marine species", "type": "n. phr.", "unit": "Unit 6", "meaning": "海洋生物"},
        {"word": "natural habitat", "type": "n. phr.", "unit": "Unit 6", "meaning": "自然栖息地"},
        {"word": "reclaim", "type": "v.", "unit": "Unit 6", "meaning": "回收利用"},
        {"word": "renewable", "type": "adj.", "unit": "Unit 6", "meaning": "可再生的"},
        {"word": "shoreline", "type": "n.", "unit": "Unit 6", "meaning": "海岸线"},
        {"word": "sustainable", "type": "adj.", "unit": "Unit 6", "meaning": "可持续的"},
        {"word": "tropical rainforest", "type": "n. phr.", "unit": "Unit 6", "meaning": "热带雨林"},
        {"word": "alternative", "type": "n.", "unit": "Unit 6", "meaning": "替代品"},
        {"word": "complicated", "type": "adj.", "unit": "Unit 6", "meaning": "复杂的"},
        {"word": "downsize", "type": "v.", "unit": "Unit 6", "meaning": "缩减规模"},
        {"word": "escalate", "type": "v.", "unit": "Unit 6", "meaning": "升级/加剧"},
        {"word": "exoskeleton", "type": "n.", "unit": "Unit 6", "meaning": "外骨骼"},
        {"word": "expel", "type": "v.", "unit": "Unit 6", "meaning": "排出/驱逐"},
        {"word": "indestructible", "type": "adj.", "unit": "Unit 6", "meaning": "不可毁灭的"},
        {"word": "outlive", "type": "v.", "unit": "Unit 6", "meaning": "比...活得长"},
        {"word": "outnumber", "type": "v.", "unit": "Unit 6", "meaning": "数量超过"},
        {"word": "outsource", "type": "v.", "unit": "Unit 6", "meaning": "外包"},
        {"word": "overburden", "type": "v.", "unit": "Unit 6", "meaning": "使负担过重"},
        {"word": "overcome", "type": "v.", "unit": "Unit 6", "meaning": "克服"},
        {"word": "overestimate", "type": "v.", "unit": "Unit 6", "meaning": "高估"},
        {"word": "overheat", "type": "v.", "unit": "Unit 6", "meaning": "过热"},
        {"word": "overpromise", "type": "v.", "unit": "Unit 6", "meaning": "信口开河/过度承诺"},
        {"word": "overreact", "type": "v.", "unit": "Unit 6", "meaning": "过度反应"},
        {"word": "overrun", "type": "v.", "unit": "Unit 6", "meaning": "泛滥/超过"},
        {"word": "potential", "type": "adj.", "unit": "Unit 6", "meaning": "潜在的"},
        {"word": "regenerate", "type": "v.", "unit": "Unit 6", "meaning": "再生"},
        {"word": "reverse", "type": "v.", "unit": "Unit 6", "meaning": "颠倒/反转"},
        {"word": "skeleton", "type": "n.", "unit": "Unit 6", "meaning": "骨骼"},
        {"word": "survival", "type": "n.", "unit": "Unit 6", "meaning": "生存"},
        {"word": "symbiotic relationship", "type": "n. phr.", "unit": "Unit 6", "meaning": "共生关系"},
        {"word": "temporary", "type": "adj.", "unit": "Unit 6", "meaning": "暂时的"},
        {"word": "underpay", "type": "v.", "unit": "Unit 6", "meaning": "支付过低"},
        {"word": "undersize", "type": "v.", "unit": "Unit 6", "meaning": "使尺寸更小"},
        {"word": "underuse", "type": "v.", "unit": "Unit 6", "meaning": "疏于使用"},
        {"word": "underweight", "type": "adj.", "unit": "Unit 6", "meaning": "过轻的"},
        {"word": "vulnerable", "type": "adj.", "unit": "Unit 6", "meaning": "脆弱的"},
        {"word": "wean", "type": "v.", "unit": "Unit 6", "meaning": "戒掉/断奶"},
        {"word": "ethnic minority", "type": "n. phr.", "unit": "Unit 7", "meaning": "少数民族"},
        {"word": "expatriate", "type": "n.", "unit": "Unit 7", "meaning": "外籍人士"},
        {"word": "single parent", "type": "n. phr.", "unit": "Unit 7", "meaning": "单亲家长"},
        {"word": "the chronically ill", "type": "n. phr.", "unit": "Unit 7", "meaning": "慢性病患者"},
        {"word": "the elderly", "type": "n. phr.", "unit": "Unit 7", "meaning": "老年人"},
        {"word": "the impoverished", "type": "n. phr.", "unit": "Unit 7", "meaning": "贫困者"},
        {"word": "the marginalized", "type": "n. phr.", "unit": "Unit 7", "meaning": "边缘化群体"},
        {"word": "the unemployed", "type": "n. phr.", "unit": "Unit 7", "meaning": "失业者"},
        {"word": "the youth", "type": "n. phr.", "unit": "Unit 7", "meaning": "青年人"},
        {"word": "alleviate", "type": "v.", "unit": "Unit 7", "meaning": "缓解"},
        {"word": "circumstance", "type": "n.", "unit": "Unit 7", "meaning": "环境/条件"},
        {"word": "complicated", "type": "adj.", "unit": "Unit 7", "meaning": "复杂的"},
        {"word": "comprise", "type": "v.", "unit": "Unit 7", "meaning": "包含，由...组成"},
        {"word": "connected", "type": "adj.", "unit": "Unit 7", "meaning": "有联系的"},
        {"word": "ease", "type": "v.", "unit": "Unit 7", "meaning": "减轻/缓解"},
        {"word": "engage", "type": "v.", "unit": "Unit 7", "meaning": "参与/吸引"},
        {"word": "equate", "type": "v.", "unit": "Unit 7", "meaning": "使等同"},
        {"word": "exacerbate", "type": "v.", "unit": "Unit 7", "meaning": "恶化/加剧"},
        {"word": "grave", "type": "adj.", "unit": "Unit 7", "meaning": "严重的"},
        {"word": "long-standing", "type": "adj.", "unit": "Unit 7", "meaning": "长期存在的"},
        {"word": "mutually beneficial", "type": "adj.", "unit": "Unit 7", "meaning": "互利的"},
        {"word": "overwhelming", "type": "adj.", "unit": "Unit 7", "meaning": "压倒性的"},
        {"word": "perspective", "type": "n.", "unit": "Unit 7", "meaning": "视角/观点"},
        {"word": "policy", "type": "n.", "unit": "Unit 7", "meaning": "政策"},
        {"word": "pose", "type": "v.", "unit": "Unit 7", "meaning": "造成/提出"},
        {"word": "pressing", "type": "adj.", "unit": "Unit 7", "meaning": "紧迫的"},
        {"word": "priority", "type": "n.", "unit": "Unit 7", "meaning": "优先级/优先事项"},
        {"word": "rectify", "type": "v.", "unit": "Unit 7", "meaning": "纠正"},
        {"word": "resolve", "type": "v.", "unit": "Unit 7", "meaning": "解决"},
        {"word": "resource", "type": "n.", "unit": "Unit 7", "meaning": "资源"},
        {"word": "root of the problem", "type": "n. phr.", "unit": "Unit 7", "meaning": "问题的根源"},
        {"word": "universal", "type": "adj.", "unit": "Unit 7", "meaning": "普遍的"},
        {"word": "unprecedented", "type": "adj.", "unit": "Unit 7", "meaning": "前所未有的"},
        {"word": "annoyance", "type": "n.", "unit": "Unit 7", "meaning": "烦恼"},
        {"word": "carefree", "type": "adj.", "unit": "Unit 7", "meaning": "无忧无虑的"},
        {"word": "desperate", "type": "adj.", "unit": "Unit 7", "meaning": "绝望的"},
        {"word": "embarrassed", "type": "adj.", "unit": "Unit 7", "meaning": "尴尬的"},
        {"word": "helplessness", "type": "n.", "unit": "Unit 7", "meaning": "无助"},
        {"word": "homesick", "type": "adj.", "unit": "Unit 7", "meaning": "想家的"},
        {"word": "hopelessness", "type": "n.", "unit": "Unit 7", "meaning": "绝望"},
        {"word": "sensitive", "type": "adj.", "unit": "Unit 7", "meaning": "敏感的"},
        {"word": "appal", "type": "v.", "unit": "Unit 7", "meaning": "使震惊"},
        {"word": "awareness", "type": "n.", "unit": "Unit 7", "meaning": "意识"},
        {"word": "benefit", "type": "n.", "unit": "Unit 7", "meaning": "利益/好处"},
        {"word": "creativity", "type": "n.", "unit": "Unit 7", "meaning": "创造力"},
        {"word": "cybercrime", "type": "n.", "unit": "Unit 7", "meaning": "网络犯罪"},
        {"word": "disparity", "type": "n.", "unit": "Unit 7", "meaning": "悬殊/差距"},
        {"word": "edible", "type": "adj.", "unit": "Unit 7", "meaning": "可食用的"},
        {"word": "epidemic", "type": "n.", "unit": "Unit 7", "meaning": "疫情/流行病"},
        {"word": "existence", "type": "n.", "unit": "Unit 7", "meaning": "存在"},
        {"word": "generosity", "type": "n.", "unit": "Unit 7", "meaning": "慷慨"},
        {"word": "hack", "type": "v.", "unit": "Unit 7", "meaning": "黑客入侵"},
        {"word": "homelessness", "type": "n.", "unit": "Unit 7", "meaning": "无家可归"},
        {"word": "ignorance", "type": "n.", "unit": "Unit 7", "meaning": "无知"},
        {"word": "inequality", "type": "n.", "unit": "Unit 7", "meaning": "不平等"},
        {"word": "inferior", "type": "adj.", "unit": "Unit 7", "meaning": "较差的/下等的"},
        {"word": "innovation", "type": "n.", "unit": "Unit 7", "meaning": "创新"},
        {"word": "insensitivity", "type": "n.", "unit": "Unit 7", "meaning": "迟钝/漠不关心"},
        {"word": "interaction", "type": "n.", "unit": "Unit 7", "meaning": "互动"},
        {"word": "isolation", "type": "n.", "unit": "Unit 7", "meaning": "隔离/孤独"},
        {"word": "mingle", "type": "v.", "unit": "Unit 7", "meaning": "混合/交往"},
        {"word": "moral", "type": "adj.", "unit": "Unit 7", "meaning": "道德的"},
        {"word": "nominate", "type": "v.", "unit": "Unit 7", "meaning": "提名/推荐"},
        {"word": "poverty", "type": "n.", "unit": "Unit 7", "meaning": "贫困"},
        {"word": "prosperous", "type": "adj.", "unit": "Unit 7", "meaning": "富裕的"},
        {"word": "recharge", "type": "v.", "unit": "Unit 7", "meaning": "充电/恢复体力"},
        {"word": "stress", "type": "n.", "unit": "Unit 7", "meaning": "压力"},
        {"word": "suffering", "type": "n.", "unit": "Unit 7", "meaning": "苦难"},
        {"word": "3D character designer", "type": "n. phr.", "unit": "Unit 8", "meaning": "3D角色设计师"},
        {"word": "artisan", "type": "n.", "unit": "Unit 8", "meaning": "工匠"},
        {"word": "beautician", "type": "n.", "unit": "Unit 8", "meaning": "美容师"},
        {"word": "chef", "type": "n.", "unit": "Unit 8", "meaning": "厨师"},
        {"word": "doctor", "type": "n.", "unit": "Unit 8", "meaning": "医生"},
        {"word": "editor", "type": "n.", "unit": "Unit 8", "meaning": "编辑"},
        {"word": "food photographer", "type": "n. phr.", "unit": "Unit 8", "meaning": "食品摄影师"},
        {"word": "forensic scientist", "type": "n. phr.", "unit": "Unit 8", "meaning": "法医学家"},
        {"word": "journalist", "type": "n.", "unit": "Unit 8", "meaning": "记者"},
        {"word": "mechanic", "type": "n.", "unit": "Unit 8", "meaning": "机械工"},
        {"word": "motion capture model", "type": "n. phr.", "unit": "Unit 8", "meaning": "动作捕捉模特"},
        {"word": "surgeon", "type": "n.", "unit": "Unit 8", "meaning": "外科医生"},
        {"word": "systems analyst", "type": "n. phr.", "unit": "Unit 8", "meaning": "系统分析师"},
        {"word": "translator", "type": "n.", "unit": "Unit 8", "meaning": "翻译"},
        {"word": "video game writer", "type": "n. phr.", "unit": "Unit 8", "meaning": "游戏编剧"},
        {"word": "virtual fashion model", "type": "n. phr.", "unit": "Unit 8", "meaning": "虚拟时装模特"},
        {"word": "vlogger", "type": "n.", "unit": "Unit 8", "meaning": "视频博主"},
        {"word": "certificate", "type": "n.", "unit": "Unit 8", "meaning": "证书"},
        {"word": "creative", "type": "adj.", "unit": "Unit 8", "meaning": "有创造力的"},
        {"word": "effective communication skills", "type": "n. phr.", "unit": "Unit 8", "meaning": "有效的沟通技巧"},
        {"word": "efficient time management skills", "type": "n. phr.", "unit": "Unit 8", "meaning": "高效的时间管理能力"},
        {"word": "empathetic", "type": "adj.", "unit": "Unit 8", "meaning": "有同理心的"},
        {"word": "flexible", "type": "adj.", "unit": "Unit 8", "meaning": "灵活的"},
        {"word": "fluent", "type": "adj.", "unit": "Unit 8", "meaning": "流利的"},
        {"word": "good problem-solving skills", "type": "n. phr.", "unit": "Unit 8", "meaning": "良好的解决问题能力"},
        {"word": "innovative", "type": "adj.", "unit": "Unit 8", "meaning": "创新的"},
        {"word": "multilingual", "type": "adj.", "unit": "Unit 8", "meaning": "使用多种语言的"},
        {"word": "organized", "type": "adj.", "unit": "Unit 8", "meaning": "有条理的"},
        {"word": "proactive", "type": "adj.", "unit": "Unit 8", "meaning": "积极主动的"},
        {"word": "productive", "type": "adj.", "unit": "Unit 8", "meaning": "富有成效的"},
        {"word": "professional", "type": "adj.", "unit": "Unit 8", "meaning": "专业的"},
        {"word": "proficiency", "type": "n.", "unit": "Unit 8", "meaning": "熟练/精通"},
        {"word": "resourceful", "type": "adj.", "unit": "Unit 8", "meaning": "足智多谋的"},
        {"word": "responsible", "type": "adj.", "unit": "Unit 8", "meaning": "负责任的"},
        {"word": "soft skills", "type": "n. phr.", "unit": "Unit 8", "meaning": "软实力/软技能"},
        {"word": "team player", "type": "n. phr.", "unit": "Unit 8", "meaning": "有团队精神的人"},
        {"word": "technical", "type": "adj.", "unit": "Unit 8", "meaning": "技术的"},
        {"word": "transferable", "type": "adj.", "unit": "Unit 8", "meaning": "可转移的"},
        {"word": "acquire", "type": "v.", "unit": "Unit 8", "meaning": "获得"},
        {"word": "analyse", "type": "v.", "unit": "Unit 8", "meaning": "分析"},
        {"word": "assist", "type": "v.", "unit": "Unit 8", "meaning": "协助"},
        {"word": "conduct", "type": "v.", "unit": "Unit 8", "meaning": "实施/执行"},
        {"word": "consult", "type": "v.", "unit": "Unit 8", "meaning": "咨询/请教"},
        {"word": "coordinate", "type": "v.", "unit": "Unit 8", "meaning": "协调"},
        {"word": "create", "type": "v.", "unit": "Unit 8", "meaning": "创造"},
        {"word": "design", "type": "v.", "unit": "Unit 8", "meaning": "设计"},
        {"word": "develop", "type": "v.", "unit": "Unit 8", "meaning": "发展/开发"},
        {"word": "employ", "type": "v.", "unit": "Unit 8", "meaning": "雇用"},
        {"word": "enhance", "type": "v.", "unit": "Unit 8", "meaning": "增强/提高"},
        {"word": "expand", "type": "v.", "unit": "Unit 8", "meaning": "扩大/拓展"},
        {"word": "implement", "type": "v.", "unit": "Unit 8", "meaning": "实施/执行"},
        {"word": "innovate", "type": "v.", "unit": "Unit 8", "meaning": "创新"},
        {"word": "intern", "type": "v.", "unit": "Unit 8", "meaning": "实习"},
        {"word": "launch", "type": "v.", "unit": "Unit 8", "meaning": "发射/投放/发起"},
        {"word": "maintain", "type": "v.", "unit": "Unit 8", "meaning": "维持/保养"},
        {"word": "mentor", "type": "v.", "unit": "Unit 8", "meaning": "指导/导师"},
        {"word": "research", "type": "v.", "unit": "Unit 8", "meaning": "研究"},
        {"word": "acknowledge", "type": "v.", "unit": "Unit 8", "meaning": "承认/致谢"},
        {"word": "candidate", "type": "n.", "unit": "Unit 8", "meaning": "候选人"},
        {"word": "complex", "type": "adj.", "unit": "Unit 8", "meaning": "复杂的"},
        {"word": "compression", "type": "n.", "unit": "Unit 8", "meaning": "压缩"},
        {"word": "concurrently", "type": "adv.", "unit": "Unit 8", "meaning": "同时地"},
        {"word": "fulfilment", "type": "n.", "unit": "Unit 8", "meaning": "满足感"},
        {"word": "hone", "type": "v.", "unit": "Unit 8", "meaning": "磨练/提高"},
        {"word": "lack", "type": "v.", "unit": "Unit 8", "meaning": "缺乏"},
        {"word": "prominent", "type": "adj.", "unit": "Unit 8", "meaning": "杰出的"},
        {"word": "pursue", "type": "v.", "unit": "Unit 8", "meaning": "追求"},
        {"word": "qualification", "type": "n.", "unit": "Unit 8", "meaning": "资格/资历"},
        {"word": "sack", "type": "v.", "unit": "Unit 8", "meaning": "解雇"},
        {"word": "simulation", "type": "n.", "unit": "Unit 8", "meaning": "模拟"},
        {"word": "simultaneously", "type": "adv.", "unit": "Unit 8", "meaning": "同时地"},
        {"word": "slash career", "type": "n. phr.", "unit": "Unit 8", "meaning": "斜杠职业"}
    ]
};
